language: java

services:
  - mysql

sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libssl1.0.0
      
matrix:
  include:
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.5.2
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.5.3
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.6.0
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.6.1
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.6.2
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.6.3
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
        - VAULT_VER=0.6.4
    - jdk: oraclejdk8
      env:
        - PROFILE=ci
    - jdk: oraclejdk8
      env:
        - PROFILE=spring5-next

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install:
  - mkdir -p download
  - src/test/bash/create_certificates.sh
  - src/test/bash/install_vault.sh
  - src/test/bash/install_consul.sh
  - src/test/bash/local_run_vault.sh &
  - src/test/bash/local_run_consul.sh &
  - mysql -e "CREATE USER 'spring' IDENTIFIED by 'vault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'spring'@'%' WITH GRANT OPTION;";
  - source src/test/bash/env.sh && src/test/bash/setup_examples.sh

script: mvn clean verify -P${PROFILE}

after_script:
  - pkill vault
  - pkill consul

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
